### ISSUE TITLE
go-nogo not saving to mysql database

### ISSUE THREAD

**Issue by tfeige91** [expfactory-experiments/go-nogo#1]
The go-nogo experiment is not able to save to the mysql database. It produces this error: 
![image](https://user-images.githubusercontent.com/8275704/95970544-5dbf0f00-0e10-11eb-8ba3-0e1117a473e0.png)

All other experiments (including self developed ones) work fine. 
Can you help me with that? -> I use it as it is here, no code changes @all.

**Comment by tfeige91** [comment]
Solved it: Changing the data type of the column _Data_ from text to **longtext** did the trick.

**Comment by vsoch** [comment]
Great to hear! And sorry for delay, it’s still early in my timezone. Please feel free to close the issue, and thanks for using expfactory!
